Gelato
0xtekgrinder/warlord-autocompounder pull request #2
Opened 2023-06-26 22:58 UTC by 0xtekgrinder

2023-06-26 22:58 UTC, 0xtekgrinder commented
Still needs to update vault addresses on deploy

2023-07-01 19:05 UTC, 0xMemoryGrinder requested changes
Check comments

2023-07-01 19:05 UTC, 0xMemoryGrinder commented on operator/src/utils/getParaswapData.ts
> +      `https://apiv5.paraswap.io/prices?srcToken=${srcToken}&destToken=${destToken}&amount=${amount.toString()}&side=SELL&network=${chainId}&srcDecimals=${srcDecimals}&destDecimals=${destDecimals}&us
This should be in a configuration attribute

2023-07-01 19:05 UTC, 0xMemoryGrinder commented on operator/src/utils/getParaswapData.ts
> +      `https://apiv5.paraswap.io/transactions/${chainId}?ignoreChecks=true&ignoreGasEstimate=true`,
This should be in a configuration attribute

2023-07-01 19:05 UTC, 0xMemoryGrinder commented on operator/src/utils/getParaswapData.ts
> +      `https://apiv5.paraswap.io/prices?srcToken=${srcToken}&destToken=${destToken}&amount=${amount.toString()}&side=SELL&network=${chainId}&srcDecimals=${srcDecimals}&destDecimals=${destDecimals}&us
You should use URL class to build the url, it is cleaner to list all query parameters

2023-07-01 21:27 UTC, 0xtekgrinder commented on operator/src/utils/getParaswapData.ts
> +      `https://apiv5.paraswap.io/prices?srcToken=${srcToken}&destToken=${destToken}&amount=${amount.toString()}&side=SELL&network=${chainId}&srcDecimals=${srcDecimals}&destDecimals=${destDecimals}&us
overpowered

2023-07-01 22:53 UTC, 0xtekgrinder commented on operator/src/index.ts
> +  const retryCompoundTask = cron.schedule(
I don't think it's needed

2023-07-01 22:54 UTC, 0xtekgrinder commented on operator/src/index.ts
> +  const retryHarvestTask = cron.schedule(
I don't think it's needed

2023-07-01 22:54 UTC, 0xtekgrinder commented on operator/src/index.ts
> +  cron.schedule("0 4 * * 0", async () => {
I don't think it's needed

2023-07-02 10:17 UTC, 0xMemoryGrinder requested changes
Check comments

2023-07-02 10:17 UTC, 0xMemoryGrinder commented on operator/src/utils/checkGasPrice.ts
> +    );
Use URL class to add query parameters

2023-07-02 10:17 UTC, 0xMemoryGrinder commented on operator/src/utils/getParaswapData.ts
> +      `${paraswapApiUrl}/prices?srcToken=${srcToken}&destToken=${destToken}&amount=${amount.toString()}&side=SELL&network=${chainId}&srcDecimals=${srcDecimals}&destDecimals=${destDecimals}&userAddres
Use URL class to add query parameters

2023-07-02 10:17 UTC, 0xMemoryGrinder commented on operator/src/utils/getParaswapData.ts
> +      `${paraswapApiUrl}/transactions/${chainId}?ignoreChecks=true&ignoreGasEstimate=true`,
Use URL class to add query parameters

2023-07-02 12:24 UTC, 0xMemoryGrinder approved these changes
LGTM

2023-07-02 12:25 UTC, merged